sudo: required

git:
  depth: 1

language: java

services:
- docker

install:
- mvn clean install --activate-profiles local -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- mvn deploy --batch-mode --show-version
